/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#3525cd',
        'primary-container': '#4f46e5',
        'on-primary': '#ffffff',
        'on-primary-container': '#dad7ff',
        secondary: '#006a61',
        'secondary-container': '#86f2e4',
        tertiary: '#7e3000',
        'tertiary-container': '#a44100',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        surface: '#f9f9ff',
        'surface-container': '#e7eeff',
        'surface-container-low': '#f0f3ff',
        'surface-container-high': '#dee8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#d8e3fb',
        'surface-variant': '#d8e3fb',
        'surface-bright': '#f9f9ff',
        background: '#f9f9ff',
        'on-surface': '#111c2d',
        'on-surface-variant': '#464555',
        'on-background': '#111c2d',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        inverse: '#263143',
        'inverse-primary': '#c3c0ff',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#351000',
        'on-secondary-fixed': '#00201d',
        'on-secondary-fixed-variant': '#005049',
        'on-tertiary-container': '#ffd2be',
        'on-tertiary-fixed-variant': '#7b2f00',
        'secondary-fixed': '#89f5e7',
        'secondary-fixed-dim': '#6bd8cb',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'surface-tint': '#4d44e3',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'mono-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        unit: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xs: '4px',
        'container-margin': '24px',
      },
      boxShadow: {
        'level-2': '0px 4px 12px rgba(30, 41, 59, 0.08)',
      },
    },
  },
  plugins: [],
};
